# cluster-wide settings
PG_BIN="/workspaces/postgres/tmp_install/usr/local/pgsql/bin"
DB_NAME="postgres"
DB_USER="vscode"
INITDB_ARGS="--no-locale -E UTF8"

# postgres settings applied on each node
MAX_PREPARED_TRANSACTIONS=100
FSYNC=off
SYNCHRONOUS_COMMIT=off
FULL_PAGE_WRITES=off
LOGGING_COLLECTOR=on
SHARED_PRELOAD_LIBRARIES="postgres_fdw"
MUX_WORKER_COUNT=3

# node list
NODES=(node1 node2)

# per-node connection info
HOST_node1="10.0.3.54"
HOST_node2="10.0.1.151"

PORT_node1=5432
PORT_node2=5432

MUX_PORT_node1=6432
MUX_PORT_node2=6432

PGDATA_node1="/var/tmp/pg_cluster/node1"
PGDATA_node2="/var/tmp/pg_cluster/node2"

CLUSTER_NAME_node1="node1"
CLUSTER_NAME_node2="node2"